name: 'Add new issue to project'
description: 'Add a new issue card to a specific column of a specific project in your repo'
inputs:
  project:
    description: 'Name of the project within the repo'
    required: true
  column:
    description: 'Name of the column within the project'
    required: true
  token:
    description: 'The generated GitHub secret scoped to the repo'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
